package shopServer.Services;

import generated.General;
import generated.serviceAddProductGrpc;
import io.grpc.stub.StreamObserver;

//First we create a class that extends the one generated by the proto file
public class AddProductService extends serviceAddProductGrpc.serviceAddProductImplBase{
    //We create the object that is gonna work with the data base
    DataBase db = new DataBase();

    @Override
    public void giveResponseAddProduct(General.ClientPetitionAddProduct request,
                                       StreamObserver<General.ServerResponseAddProduct> responseObserver){
        System.out.println("<------------------------ADD PRODUCT REQUEST----------------------------->");
        General.ServerResponseAddProduct response;
        try{
            //First we display in the log the new product
            System.out.println("Inserting a new product:\n"+request.getName()+", "+request.getOwner()+", "+
                    request.getPrice()+", "+request.getSale()+", "+request.getImagePath()+", "+
                    request.getUnitsExistence()+", "+request.getCategory());

            db.insert("Insert into product(name, price, unitsInExistence, sale, imagePath, owner, category) " +
                    "values ('"+request.getName()+"', '"+request.getPrice()+"', '"+request.getUnitsExistence()+"', '"
                    +request.getSale()+"', '"+request.getImagePath()+"', '"+request.getOwner()+"', '"+
                    request.getCategory()+"');");

            response = General.ServerResponseAddProduct.newBuilder()
                    .setStatusCode(General.ServerResponseAddProduct.StatusCode.OK)
                    .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }catch(Exception e){
            System.out.println("/////////////////////////////////ADD PRODUCT ERROR//////////////////////////////////\n"+
                    e.getLocalizedMessage());
            //As there was some kind of error we create a response with and Status Code explaining to the Client that
            //there was an error in the server
            response = General.ServerResponseAddProduct.newBuilder()
                    .setStatusCode(General.ServerResponseAddProduct.StatusCode.SERVER_ERROR)
                    .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }
    }
}
