package shopServer.Services;

import generated.General;
import generated.serviceAddUserGrpc;
import io.grpc.stub.StreamObserver;

import java.util.ArrayList;

//First we create a class that extends the one generated by the proto file
public class AddUserService extends serviceAddUserGrpc.serviceAddUserImplBase{
    //We create the object that is gonna work with the data base
    DataBase db = new DataBase();

    @Override
    public void giveResponseAddUser(General.ClientPetitionAddUser request,
                                     StreamObserver<General.ServerResponseAddUser> responseObserver) {
        System.out.println("<------------------------ADD USER REQUEST----------------------------->");
        General.ServerResponseAddUser response;
        try{
            //First we display in the log the user that is going to be added to the DB
            System.out.println("Inserting a new user:\n"+request.getType()+", "+request.getNick()
                    +", "+request.getName()+", "+request.getSurName()+", "+
                    request.getPhone()+", "+request.getAdress()+", "+request.getImagePath()+", "+
                    request.getPwd());

            db.modify("Insert into user (type, nickName, name, surname, phone, address, imagePath, pwd) values " +
                    "('"+request.getType()+"', '"+request.getNick()+"', '"+request.getName()+"', '"
                    +request.getSurName()+"', '"+ request.getPhone()+"', '"+request.getAdress()+"', '"
                    +request.getImagePath()+"', '"+ request.getPwd()+"');");
            //Then we create the response with a Status Code that will tell the client that the new user was added
            //successfully
            response= General.ServerResponseAddUser.newBuilder()
                    .setStatusCode(General.ServerResponseAddUser.StatusCode.OK)
                    .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }catch(Exception e){
            System.out.println("/////////////////////////////////ADD USER ERROR/////////////////////////////////////\n"+
                    e.getLocalizedMessage());
            //As there was some kind of error we create a response with and Status Code explaining to the Client that
            //there was an error in the server
            response = General.ServerResponseAddUser.newBuilder()
                    .setStatusCode(General.ServerResponseAddUser.StatusCode.SERVER_ERROR)
                    .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }
    }
}
