package shopServer.Services;

import generated.General;
import generated.serviceUpdateUserDataGrpc;
import io.grpc.stub.StreamObserver;

//First we create a class that extends the one generated by the proto file
public class ChangeUserService extends serviceUpdateUserDataGrpc.serviceUpdateUserDataImplBase{
    //We create the object that is gonna work with the data base
    DataBase db = new DataBase();

    @Override
    public void giveResponseUpdateUserData(General.ClientPetitionUpdateUserData request,
                                           StreamObserver<General.ServerResponseUpdateUserData> responseObserver){
        System.out.println("<--------------------CHANGE USER DATA REQUEST------------------------------------------>");
        General.ServerResponseUpdateUserData response;
        try{
            //Now we show the data input in the log
            System.out.println("User data: \n"+request.getIdUser()+", "+request.getName()+", "+request.getSurName()+
                    ", "+request.getPhone()+", "+request.getAddress()+", "+request.getType());
            if(!request.getName().isEmpty())
                db.modify("update user set name ='"+request.getName()+"' where idUser = '"+request.getIdUser()+"'");

            if(!request.getSurName().isEmpty())
                db.modify("update user set surname ='"+request.getSurName()+
                        "' where idUser = '"+request.getIdUser()+"'");
            if(!request.getPhone().isEmpty())
                db.modify("update user set phone ='"+request.getPhone()+"' where idUser = '"
                        +request.getIdUser()+"'");
            if(!request.getAddress().isEmpty())
                db.modify("update user set address ='"+request.getAddress()+"' where idUser = '"
                        +request.getIdUser()+"'");
            if(request.getType() != -1)
                db.modify("update user set type ='"+request.getType()+"' where idUser = '"
                        +request.getIdUser()+"'");
            response = General.ServerResponseUpdateUserData.newBuilder()
                    .setStatusCode(General.ServerResponseUpdateUserData.StatusCode.OK)
                    .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }catch(Exception e){
            System.out.println("////////////////////////////CHANGE USER DATA ERROR/////////////////////////////////\n"+
                    e.getLocalizedMessage());
            //As there was some kind of error we create a response with and Status Code explaining to the Client that
            //there was an error in the server
            response = General.ServerResponseUpdateUserData.newBuilder()
                    .setStatusCode(General.ServerResponseUpdateUserData.StatusCode.SERVER_ERROR)
                    .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }
    }
}
