package shopServer.Services;

import generated.General;
import generated.serviceUserDataGrpc;
import io.grpc.stub.StreamObserver;

import java.util.ArrayList;

//First we create a class that extends the one generated by the proto file
public class UserDataService extends serviceUserDataGrpc.serviceUserDataImplBase{
    //We create the object that is gonna work with the data base
    DataBase db = new DataBase();


    @Override
    public void giveResponseUserData(General.ClientPetitionUserData request,
                                     StreamObserver<General.ServerResponseUserData> responseObserver){
        System.out.println("<------------------------USER DATA REQUEST----------------------------->");
        General.ServerResponseUserData response;
        try{
            //First we make the consult and display the result in the server log
            ArrayList<ArrayList<Object>> userData = db.consult("SELECT name, surname, phone, address," +
                    " imagePath FROM user WHERE idUser = "+ request.getIdUser()+";");
            System.out.println("Result: "+userData);
            //We create the response of the server and put the result on it

            response = General.ServerResponseUserData.newBuilder()
                    .setName(userData.get(0).get(0).toString())
                    .setSurname(userData.get(0).get(1).toString())
                    .setPhone(userData.get(0).get(2).toString())
                    .setAdress(userData.get(0).get(3).toString())
                    .setImagePath(userData.get(0).get(4).toString())
                    .setStatusCode(General.ServerResponseUserData.StatusCode.OK)
                    .build();

            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }catch(Exception e){
            System.out.println("/////////////////////////////////USER DATA ERROR//////////////////////////////////\n"+
                    e.getLocalizedMessage());
            //As there was some kind of error we create a response with and Status Code explaining to the Client that
            //there was an error in the server
            response = General.ServerResponseUserData.newBuilder()
                    .setStatusCode(General.ServerResponseUserData.StatusCode.SERVER_ERROR)
                    .build();
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        }
    }

}
